# Workspace file for portagenty. See:
# https://cybersader.github.io/portagenty/reference/schema/
name = "cyberbase"
id = "a5236942-2967-4cc6-b521-ba1009b75859"
multiplexer = "zellij"

[[session]]
name = "shell"
cwd = "."
command = "bash"
kind = "shell"
